# Generated by Django 6.1 on 2026-09-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cash_flow_category',
            field=models.CharField(choices=[('OPERATING', 'Operating'), ('INVESTING', 'Investing'), ('FINANCING', 'Financing'), ('NONE', 'Not Applicable')], default='NONE', max_length=20),
        ),
    ]
