# Generated by Django 6.1 on 2026-08-31 09:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('operations', '0003_sale_saleitem_sale_unique_sale_number_per_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_number', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_pumps', to='companies.company')),
            ],
            options={
                'ordering': ['pump_number'],
            },
        ),
        migrations.CreateModel(
            name='PumpAttendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pump_attendants', to='companies.company')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='PumpSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('opening_meter', models.DecimalField(decimal_places=3, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('closing_meter', models.DecimalField(decimal_places=3, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('litres_sold', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('price_per_litre', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('MOBILE_MONEY', 'Mobile Money'), ('CARD', 'Card'), ('CREDIT', 'Credit')], default='CASH', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('VOIDED', 'Voided')], default='DRAFT', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pump_sales', to='operations.pumpattendant')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pump_sales', to='companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pump_sales_created', to=settings.AUTH_USER_MODEL)),
                ('fuel_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pump_sales', to='operations.product')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pump_sales', to='operations.fuelpump')),
            ],
            options={
                'ordering': ['-sale_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='fuelpump',
            constraint=models.UniqueConstraint(fields=('company', 'pump_number'), name='unique_pump_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='pumpattendant',
            constraint=models.UniqueConstraint(fields=('company', 'employee_code'), name='unique_attendant_code_per_company'),
        ),
    ]
