# Generated by Django 6.1 on 2026-09-01 09:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar (USD)'), ('LRD', 'Liberian Dollar (LRD)')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='invoice',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Number of company functional currency units equal to 1 unit of invoice currency.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
    ]
