# Generated by Django 6.1 on 2026-08-31 15:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payrolldeductiontype_payrolldeduction_payrollrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRemittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('remittance_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank')], default='BANK', max_length=20)),
                ('reference', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_remittances_created', to=settings.AUTH_USER_MODEL)),
                ('deduction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittances', to='payroll.payrolldeductiontype')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittances', to='payroll.payrollperiod')),
            ],
            options={
                'ordering': ['-remittance_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('payroll_period', 'deduction_type', 'reference'), name='unique_payroll_remittance_reference')],
            },
        ),
    ]
