# Generated by Django 6.1 on 2026-09-07 11:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_currency'),
        ('payroll', '0005_payrollremittance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='annual_taxable_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='paye_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='taxable_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.CreateModel(
            name='PayrollTaxBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lower_limit', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('rate', models.DecimalField(decimal_places=4, help_text='Tax rate as a percentage, e.g. 15.00 for 15%.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fixed_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax accumulated before this band.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_tax_bands', to='companies.company')),
            ],
            options={
                'ordering': ['lower_limit', 'id'],
                'constraints': [models.UniqueConstraint(fields=('company', 'lower_limit'), name='unique_payroll_tax_band_lower_limit_per_company')],
            },
        ),
    ]
