# Generated by Django 6.1 on 2026-09-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar (USD)'), ('LRD', 'Liberian Dollar (LRD)')], default='USD', max_length=3),
        ),
    ]
